"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.

4613732
"""


def generate_fibonacci_sequence(term_limit, first_term, second_term):
    sequence = [first_term, second_term]
    while True:
        next_number = sequence[-1] + sequence[-2]
        if next_number < term_limit:
            sequence.append(next_number)
        else:
            break

    return sequence


four_m = generate_fibonacci_sequence(4000000, 1, 2)
print(sum([n for n in four_m if n % 2 == 0]))