trigger:
  tags:
    include:
      - v*

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: build_job
        displayName: Build Job
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.x"
            displayName: "Use Python 3.x"
  - stage: dev
    displayName: Deploy to Dev
    dependsOn:
      - build
    condition: succeeded()
    jobs:
      - deployment: VMDeploy
        displayName: unchained
        environment:
          name: unchained
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
              - task: ArchiveFiles@2
                inputs:
                  rootFolderOrFile: $(Build.SourcesDirectory)
              - task: CopyFiles@2
                displayName: Copy unchained files
                inputs:
                  SourceFolder: $(Build.SourcesDirectory)
                  Contents: '**'
                  TargetFolder: $(Build.ArtifactStagingDirectory)
                  CleanTargetFolder: true
