trigger:
  tags:
    include:
      - v*

jobs:
- deployment: VMDeploy
  displayName: unchained
  environment:
    name: unchained
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - script: ls