trigger:
  tags:
    include:
      - v*

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: build_job
        displayName: Build Job
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.x"
            displayName: "Use Python 3.x"
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: $(Build.SourcesDirectory)
              archiveFile: $(Build.SourcesDirectory)/sample.zip
          - publish: $(Build.SourcesDirectory)/sample.zip
            displayName: "Publishing artifact"
            artifact: sampleArtifact
  - stage: dev
    variables:
      HomePath: "/home/pipelinedump"
    displayName: Deploy to Dev
    dependsOn:
      - build
    condition: succeeded()
    jobs:
      - deployment: VMDeploy
        displayName: unchained
        environment:
          name: unchained
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
              - task: DeleteFiles@1
                inputs:
                  source: $(HomePath)
              - task: DownloadPipelineArtifact@2
                inputs:
                  source: current
                  artifact: sampleArtifact
                  path: $(HomePath)