trigger:
  tags:
    include:
      - v*

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: build_job
        displayName: Build Job
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.x"
            displayName: "Use Python 3.x"
          - script: pwd
  - stage: dev
    displayName: Deploy to Dev
    dependsOn:
      - build
    condition: succeeded()
    jobs:
      - deployment: VMDeploy
        displayName: unchained
        environment:
          name: unchained
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
              - script: pwd