trigger:
  tags:
    include:
      - v*

variables:
  AgentDeployPath: "/home/pipelinedump"
  UnchainedArchiveName: "unchained.zip"
  UnchainedArtifactName: "unchainedArtifact"

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: build_job
        displayName: Build Job
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.x"
            displayName: "Use Python 3.x"
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: $(Build.SourcesDirectory)
              archiveFile: $(Build.SourcesDirectory)/$(UnchainedArchiveName)
          - publish: $(Build.SourcesDirectory)/$(UnchainedArchiveName)
            displayName: "Publishing artifact"
            artifact: $(UnchainedArtifactName)
  - stage: dev
    displayName: Deploy to Dev
    dependsOn:
      - build
    condition: succeeded()
    jobs:
      - deployment: VMDeploy
        displayName: unchained
        environment:
          name: unchained
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
              - task: DeleteFiles@1
                inputs:
                  source: $(AgentDeployPath)
                  contents: |
                    **/*
              - task: DownloadPipelineArtifact@2
                inputs:
                  source: current
                  artifact: $(UnchainedArtifactName)
                  path: $(AgentDeployPath)